### ISSUE TITLE
Evaluate Current Schema.org Data

### ISSUE THREAD

**Issue by robneu** [wpsitecare/carelib#12]
The Schema.org spec has changed a lot recently and I think we have a few items that need to be updated and improved. The first one that comes to mind is the way we're handling images.

**Comment by robneu** [comment]
So, uh, it seems like Google pretty much doesn't give a shit about schema markup unless it's for something they want to mark up in the SERPs.

As far as I can tell, there's no real benefit to having the data on your site for anything that isn't listed on [this page](https://developers.google.com/structured-data/). Even some of the things on there really don't matter much. Articles are basically worthless unless you're a news outlet or you're setting things up for AMP, which is probably a separate thing entirely...

So, I guess the question is do we care?

**Comment by jocastaneda** [comment]
I only say yes because there are other search engines that may use it as well:
https://www.bing.com/webmaster/help/marking-up-your-site-with-structured-data-3a93e731

And yes, I did just pull that link from `Bing`. Now I have to go sanitize the room.

**Comment by robneu** [comment]
I think at the very least we need to consider dropping the BlogPosting schema and remove any associated properties. The way Schema.org 2.0 and Google treats Articles makes it extremely difficult to conform to what they're asking for and there's no clear benefit to using it for most websites.

If you're running a news site or working with AMP, it's probably worthwhile to go through the extra steps required to validate these listings, but it shouldn't be the default anymore.

**Comment by robneu** [comment]
This is done. I'll leave this open for discussion for a while, so if anyone feels strongly about how we're handling this, now would be your time to make your case. If anyone can convince me to integrate support for Articles/AMP as the default I'll revert that commit and we'll build out more advanced functionality for images, logos, and everything else [required here](https://developers.google.com/search/docs/data-types/articles).

Personally, I think it might be time to move away from structured markup in the framework entirely. JSON-LD seems like a much better format than inline structured markup and more sites are starting to support it.

**Comment by robneu** [comment]
I think we're probably good to go on this. It adds a little more work for when schema is necessary for some reason, but aside from that I think everything is 👍
